---
title: "Malaria"
output: 
  html_document:
    toc: true
    toc_float: true

---

### Background

Malaria is a vector borne disease that is preventable and curable. The parasite responsible for causing malaria is Plasmodium _spp_. There are 5 known species of this parasite, but _P. falciparum_ and _P. vivax_ pose the greatest risks in some countries. These parasites are carried by the female anopheles mosquito.  


Based on the World Health Organization (WHO) report, we have gathered data on 19 countries of interest where the incidence rates of Malaria and Malaria mortality is high and we have used some statistical tools to analyze the data. The observation period spans years 2010 to 2018.


These countries are: Nigeria, Democratic Republic of the Congo, Uganda, Mozambique, Côte d'Ivoire, Niger, Burkina Faso, Mali, Angola, United Republic of Tanzania, India, Ghana, Cameroon, Rwanda, Benin, Malawi, Kenya, Guinea, Burundi. Most of these countries are located in sub-Saharan Africa and according to the WHO, they bear the global burden of the disease.


Malaria is more common in regions with high humidity and rainfall. The people at most risk for malaria include
infants, children under 5, pregnant women, HIV/AIDS patients, non-immune migrants, and travelers. The bulk of the disease burden is carried by sub-Saharan Africa as well as the mortality cases.


Learn more about malaria by clicking the links in the navigation bar.

### Symptoms

Usually, Malaria symptoms appear between 10 to 15 days of infective mosquito bite. Malaria may cause fever, headache and chills. In severe cases, multi-organ failure may occur. Immediate treatment is often required at this stage to prevent the illness from progressing to a more severe state or even death. 

In children, a few additional symptoms may be observed such as severe anaemia, respiratory distress, and /or cerebral malaria. In places where malaria is endemic, it is not uncommon for people to develop partial immunity.

### Malaria Eradication

The war against malaria continues to be waged. The eradication of Malaria requires deliberate activities that distorts or breaks the transmission pathway as well as the employment of measures such as surveillance, diagnosis and prompt treatments. In the past few years, some countries is several regions of the world have been able to reduce their indigenous cases to 0 for 3 consecutive years.

Two major concerns in this fight against malaria is the insecticide resistance of some mosquito species and recurring anti-malaria drug resistance.
