---
title: "Proposal"
author: "Team Malaria"
date: "11/6/2020"
output: github_document
---

**The group members**

Wura Olawole (wo2179) <br>
Hanfei Qi (hq2182)<br>
Murrel Pereira (mwp2123)<br>
Laura Gomez Merchan (lcg2154)<br>
Nidhi Patel (np2619)<br>

**Tentative title**

Team Malaria (we're workshoping it)

**The motivation**

Although America is not a malaria hotspot, half the world's population lives in high risk malaria transmission regions. We searched for data and found a great set that catalogs malaria incidence, mosquito prevalence, mosquito species, among other variables. *We hope to inform the class (and public) about malaria and its vectors.* 
We found mosquito species and its causal relationship to malaria, demographics, and other species to be interesting as well!

**The intended final products**

*   What is the relationship between species of mosquitoes? 
    *   Can we visualize evolution of species over time?
    *   Is there overlap of mosquito species?
    *   Is the proportion of mosquito species the same across all continents?
    *   Do the rates of evolution change over time (how long were a species dominant during a time period?)
*   Trends over years
    *   Heat, precipitation, vegetation, etc over a year with mosquito prevalence/malaria incidence
*   Do areas with higher sickle cell traits have less malaria incidence?
*   Compare time periods

Potential ideas:

*   Climate change and mosquito prevalence
*   Relation of species genotypes 
*   Health education
*   Topography
*   Drop in malaria incidence with introduction of interventions (nets, etc)
*   Severity of malaria in relation to species/time

**The anticipated data sources**

[Malaria Atlas Species and Parasites](https://malariaatlas.org/api-docs/) <br>
[Malaria Atlas Mortality](https://malariaatlas.org/malaria-burden-data-download/) <br>
[Hydro-climate](https://archive.researchdata.leeds.ac.uk/715/) <br>
[Net mapping](https://figshare.com/articles/LLIN_Raw_Data_xlsx/12552137/1)


**The planned analyses / visualizations / coding challenges**

*   Planned analysis
    * We want to see the proportion of mosquito species across the different continent and relationship to malaria incidence
*   Visualizations
    *   A time series (2000-2017) world map with mosquito species prevalence 
        *   Maybe screenshots of year to year or a more smooth graphic?
    *   Incidence of malaria
    *   Genealogy of mosquito species
    *   Relationship with climate and malaria transmission
*   Coding challenge
    *   We want to create a genotype mapping visual of mosquito species. We have not found an available dataset with this data. Our potential solution is to use Selector Gadget and pull information from Wikipedia, which sounds tedious.  
    *   Time series world map
    *   Missing data

**The planned timeline**

*   Bi-weekly team meetings
*   Steps:
    *   Nov 7-10:  Clean data
        * Nov 11 meeting: Clean data, test out visualizations on Madagascar
    *   Nov 11-16: Build visualizations
    *   Nov 17-19: Clean up visualizations
    *   Nov 20-21: Layout
    *   Nov 22-25: Write report; tell a story
    *   Nov 28-30: Make presentation
    *   Dec 1-4:   Record
