---
title: "Project Report"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, echo = FALSE, message = FALSE, warning=FALSE}
library(tidyverse)
library(malariaAtlas)
library(leaflet)
library(ggridges)
library(readxl)
library(plotly)
library(patchwork)

knitr::opts_chunk$set(
  fig.width=6,
  fig.asp=.9,
  out.width ="90%"
)

theme_set(theme_minimal() +theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete=scale_fill_viridis_d
```

## Motivation
Although America is not a malaria hotspot, according to CDC, half of the world's population lives in high risk malaria transmission regions. Our interest in Malaria stems from our individual experiences with Malaria has most of us have ties to countries that have high prevalence of Malaria. In exploring different data sets we found some interesting patterns. Most importantly, we found that Malaria can be eradicated even in countries that are current hot spots if proper preventive measures are followed.


Malaria is a vector borne disease that is preventable and curable. The parasite responsible for causing malaria is Plasmodium _spp_. These parasites are carried by the female anopheles mosquito. Malaria is more common in regions with high humidity and rainfall. The people at most risk for malaria include; infants, children under 5, pregnant women, HIV/AIDS patients, non-immune migrants, and travelers. 

## Related work
[World Malaria Report 2019](https://www.who.int/publications/i/item/9789241565721)

The World Malaria Report provides annual updates on Malaria trends around the world. The report also contains information about yearly investments, research and tracks the progress of all intervention areas. The information provided in the report is often received from national malaria control programmes in endemic countries


[Malaria Atlas Project](https://cran.r-project.org/web/packages/malariaAtlas/vignettes/overview.html)

Malaria Atlas project is a platform that disseminates Malaria data via their Repository for Open Access Data (ROAD-MAP) project. On this platform one can find spatial distribution of Malaria prevalence, incidence, intervention and other important Malaria topics.

## Initial questions
The following were initial questions we tried to answer at the beginning. 

*   What is the relationship between species of mosquitoes? 
    *   Can we visualize evolution of species over time?
    *   Is there overlap of mosquito species?
    *   Is the proportion of mosquito species the same across all continents?
    *   Do the rates of evolution change over time (how long were a species dominant during a time period?)
*   Trends over years
    *   Heat, precipitation, vegetation, etc over a year with mosquito prevalence/malaria incidence
*   Do areas with higher sickle cell traits have less malaria incidence?
*   Compare time periods

Due to scarcity of data, we were unable to explore some of the initial questions we had set out to answer. As we continued to work with the datasets we had we were able to gete a feel for the questions we could answer given the limitations of our data.

Furthermore, in order to get the most out of our data, we filtered by a list of our countries of interest. These countries of interest according to WHO had the highest prevalence and incidence of Malaria. This way, we focused more on data from critical countries.

### Reasons why we ask those questions



## Data: Source, scraping method, cleaning, etc.

### Explore Cases

### Causes

For vectors (mosquitoes) and parasites of Malaria, We used vector data from Malaria Atlas Project, and parasite data from WHO Malaria Report 2019. The Malaria Atlas data was already tidy, so we only had to filter by our countries of interest. The WHO data on the other hand needed to be cleaned up. The original data had 11 variables: Country/area, year, 2010 to 2018 (each year was one variable). The final tidied data contained four variables: country, species, years, and cases. After tidying the data, Only _P. falciparum_ and _P.vivax_ parasite species remained because they were the predominant causes of Malaria in our countries of interest.

### Correlations

### Interventions



## Exploratory analysis

### Explore Cases

### Causes

Since the mosquito species data had small sample size (< 30 for most species) and not consistent across years, we used maps to visualize cumulative number of different mosquito species for Africa and Asia. Most malaria cases were diagnosed in these regions. For confirmed cases by parasite species, we plotted line plots of confirmed cases by _P. falciparum_ in countries of interest, from 2010 to 2018, since it was the dominant cause of malaria for most countries. Additionally, a plot for confirmed cases by _P. vivax_ in India because only India had consistent data for both _P. falciparum_ and _P. vivax_, and the numbers were quite similar.

### Correlations

### Interventions




## Additional analysis





## Discussion